
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVISION LPAREN MINUS NUMBER PLUS RPAREN TIMESexpression : expression expression PLUSexpression : expression expression MINUSexpression : termterm : expression expression TIMESterm : expression expression DIVISIONterm : factorfactor : NUMBERfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'DIVISION':([1,2,4,7,8,9,10,11,12,],[-3,-7,-6,9,-8,-5,-4,-1,-2,]),'RPAREN':([1,2,4,6,8,9,10,11,12,],[-3,-7,-6,8,-8,-5,-4,-1,-2,]),'NUMBER':([0,1,2,3,4,5,6,7,8,9,10,11,12,],[2,-3,-7,2,-6,2,2,2,-8,-5,-4,-1,-2,]),'TIMES':([1,2,4,7,8,9,10,11,12,],[-3,-7,-6,10,-8,-5,-4,-1,-2,]),'PLUS':([1,2,4,7,8,9,10,11,12,],[-3,-7,-6,11,-8,-5,-4,-1,-2,]),'LPAREN':([0,1,2,3,4,5,6,7,8,9,10,11,12,],[3,-3,-7,3,-6,3,3,3,-8,-5,-4,-1,-2,]),'MINUS':([1,2,4,7,8,9,10,11,12,],[-3,-7,-6,12,-8,-5,-4,-1,-2,]),'$end':([1,2,4,5,8,9,10,11,12,],[-3,-7,-6,0,-8,-5,-4,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,3,5,6,7,],[1,1,1,1,1,]),'expression':([0,3,5,6,7,],[5,6,7,7,7,]),'factor':([0,3,5,6,7,],[4,4,4,4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression expression PLUS','expression',3,'p_expression_plus','parser_rules.py',5),
  ('expression -> expression expression MINUS','expression',3,'p_expression_minus','parser_rules.py',9),
  ('expression -> term','expression',1,'p_expression_term','parser_rules.py',13),
  ('term -> expression expression TIMES','term',3,'p_term_times','parser_rules.py',17),
  ('term -> expression expression DIVISION','term',3,'p_term_division','parser_rules.py',21),
  ('term -> factor','term',1,'p_term_factor','parser_rules.py',25),
  ('factor -> NUMBER','factor',1,'p_factor_num','parser_rules.py',29),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','parser_rules.py',33),
]
